### ISSUE TITLE
Tiles can't be rendered when not using the default 8080 port.

### ISSUE THREAD

**Issue by Roan-V** [pl3xgaming/Pl3xMap-Fabric#1]
The mod cannot request information from the server when not using the default 8080 port.
Communication between the server plugin and the client mod to make sure the correct port is used would be the preferred fix if possible, otherwise a port config setting would be needed.

Full log here for completeness, errors starting at line 268
https://mclo.gs/Owl7ZPF#L268

**Comment by BillyGalbreath** [comment]
Did you set the correct address and port in your plugin config.yml?

Example:
```yaml
settings:
  web-address: http://localhost:8080
  language-file: lang-en.yml
  debug-mode: false
```

**Comment by Roan-V** [comment]
yup, I also tried 0.0.0.0 instead of localhost
web-address is currently set to: "http://localhost:20000"
internal-webserver.bind and .port are 0.0.0.0 and 20000 respectively (web version works fine)

I also did a server restart, a client restart and a clearing of the pl3xmap folder on the client between changes


Setting the web-address to: "http://localhost:8080" and internal-webserver.bind and .port to 0.0.0.0 and 8080 respectively had it work fine

**Comment by BillyGalbreath** [comment]
I just used localhost as an example. It has to be the web address you put into your browser... It must be reachable from the client ;)

**Comment by Roan-V** [comment]
I thought 0.0.0.0 would've worked...
Thanks :P
