### ISSUE TITLE
Minimap appears despite being disabled when relogging

### ISSUE THREAD

**Issue by Encode42** [pl3xgaming/Pl3xMap-Fabric#2]
When the minimap is disabled, and the client rejoins a server with Pl3xMap support, the minimap still appears. It can be disabled again by toggling the setting on then off.

![image](https://user-images.githubusercontent.com/34699884/129082538-0f0a7fb2-96e8-4213-a7e4-d4ff6799a859.png)

**Comment by BillyGalbreath** [comment]
https://github.com/pl3xgaming/Pl3xMap-Fabric/commit/a3a85ce1cb31eda1aec3dad21d8ba0d8ed65e30b
