### ISSUE TITLE
Map still shows when you connect to a new server

### ISSUE THREAD

**Issue by Inxity** [pl3xgaming/Pl3xMap-Fabric#3]
When you play in a pl3xmap enabled map, then switch the server in the same network it does not remove the old map
![image](https://user-images.githubusercontent.com/61350916/129238032-5ed9a21a-1b7d-4c49-9671-92a9563bffeb.png)

**Comment by BillyGalbreath** [comment]
Ohh, I didnt even think about proxied servers.. hmm, this is going to take some thinking to resolve, because the client doesnt know it switched servers

**Comment by Inxity** [comment]
Also, i can reproduce the issue even if i disconnect from this server and connect to another server, here is a photo from my local server
![image](https://user-images.githubusercontent.com/61350916/129285203-bd65090c-001b-47b6-8b0a-44fcb69e8180.png)

**Comment by BillyGalbreath** [comment]
This should be fixed with v1.2 - let me know

**Comment by Inxity** [comment]
yep, it is
